### ISSUE TITLE
Cant see Elements

### ISSUE THREAD

**Issue by chainzz** [spacedeck/spacedeck-open#9] opened 2018-03-30 19:24 UTC
Nope didnt solved the first Issue. After logging in I only see this:

http://prntscr.com/iynpl7

**Comment by mntmn** [comment] 2018-03-30 19:32
The comment in the other issue was referring to your second problem, regarding email credentials. Setting the env var will disable email sending via SES.

Back to your login problem. Please open the Javascript Console before logging in to see if there are any errors reported. Also, it is not possible to see from your screenshot what browser you are using. What is your setup (versions of node, browser)? What are the steps you are using to start the service?

**Comment by chainzz** [comment] 2018-03-30 19:43
Sorry, I'm new to Web Development. My npm version is 5.6.0 and I use Chrome Version 65.0.3325.181 .
http://prntscr.com/iyo02w thats the output of the Javascript console before logging in.

**Comment by chainzz** [comment] 2018-03-30 19:43
And I start the service using npm start

**Comment by chainzz** [comment] 2018-03-30 19:45
My node version is 8.9.4

**Comment by mntmn** [comment] 2018-03-30 19:48
OK, thanks. When you press the login button, what happens in the console then? (Leave it open)

**Comment by mntmn** [comment] 2018-03-30 19:50
Also, please copy & paste the console output of the service on startup here.

**Comment by chainzz** [comment] 2018-03-30 19:54
Thats the output on startup: http://prntscr.com/iyo5d8
After logging in: http://prntscr.com/iyo5zc

**Comment by mntmn** [comment] 2018-03-30 20:13
OK, thanks. It looks like you have a valid session but the user could not be loaded. Please copy and paste the complete output of the service (node) console after logging in.

Also, if you go to the "Application" tab in web inspector, and click on "Cookies" on the left side, and then on the website entry directly below it (should be http://localhost:9666) there should be a cookie called "sdsession" on the right side. Please post a screenshot of that.

**Comment by chainzz** [comment] 2018-03-30 20:17
Output after logging in: http://prntscr.com/iyogwb
There is no "sdsession" cookie. There are only these ones: http://prntscr.com/iyohml

**Comment by mntmn** [comment] 2018-03-30 20:44
OK, there's probably a cookie/domain problem. Please pull the latest master commit, I just merged a bunch of fixes. Then try again.

**Comment by mntmn** [comment] 2018-03-30 20:46
Please note that the localhost port has changed to 9666 in the latest version, so you have to point your browser to `http://localhost:9666/`

**Comment by chainzz** [comment] 2018-03-30 21:03
Thanks, but still doesnt work. http://prntscr.com/iyp33d

**Comment by chainzz** [comment] 2018-03-30 21:06
And this is the output of the console: http://prntscr.com/iyp4ib

**Comment by mntmn** [comment] 2018-03-30 21:10
OK, but now we can see the issue. The problem is that your MongoDB version is too new for the version of Mongoose we use. To make it work now, you would have to downgrade MongoDB to 3.4. I can fix it later to make it work for newer MongoDB versions.

**Comment by chainzz** [comment] 2018-03-30 21:14
Okay thanks a lot!! I downgraded my MongoDB and it works fine now :D

**Comment by mntmn** [comment] 2018-03-30 21:18
Nice! Thanks for testing. I will update the README.

**Closed by mntmn** 2018-03-30 21:18 UTC
