### ISSUE TITLE
scribble

### ISSUE THREAD

**Issue by Maninarang** [spacedeck/spacedeck-open#7] opened 2018-01-27 08:39 UTC
when we draw a scribble..it takes couple of second or have to hold the mouse for some time to actualy draw.. how  to reduce that time??

**Comment by Maninarang** [comment] 2018-02-01 04:19
any sugestion on this please??

**Comment by Maninarang** [comment] 2018-02-07 14:18
actualy i tried a lot but could find a solution for this.. this is very imp for me.. if you could spare some time..it will be very helpful..
Thanks

**Comment by mntmn** [comment] 2018-03-30 19:19
Closing because there was no way provided to reproduce the issue.

**Closed by mntmn** 2018-03-30 19:19 UTC
