### ISSUE TITLE
Deletion of a user account is not possible

### ISSUE THREAD

**Issue by togir2** [spacedeck/spacedeck-open#62] opened 2020-05-31 19:52 UTC
The deletion of an account is not possible.
I tried to delete a tesaccount I created but the "Terminate account" button does nothing.

The log prints a SequelizeForeignKeyConstraintError.

spacedeck_1  | [2020-05-31T19:47:52.709Z] Executing (default): DELETE FROM `users` WHERE rowid IN (SELECT rowid FROM `users` WHERE `_id` = '3cf5c610-e424-4edd-a9ea-6c8cbb3ea048' LIMIT 1)

spacedeck_1  | [2020-05-31T19:47:52.713Z] Unhandled rejection SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
spacedeck_1  |     at Query.formatError (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:382:18)
spacedeck_1  |     at Statement.afterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
spacedeck_1  |     at Statement.wrappedAfterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
spacedeck_1  |     at Statement.replacement (/app/node_modules/sqlite3/lib/trace.js:19:31)
spacedeck_1  |     at Statement.replacement (/app/node_modules/sqlite3/lib/trace.js:19:31)
spacedeck_1  | [2020-05-31T19:48:40.811Z] websocket closed:  undefined undefined
spacedeck_1  | [2020-05-31T19:48:40.811Z] [websockets] socket undefined went offline in space undefined
spacedeck_1  | [2020-05-31T19:48:40.811Z] websocket not found to remove
spacedeck_1  | [2020-05-31T19:48:40.812Z] [websockets] socket undefined went offline in space null
spacedeck_1  | [2020-05-31T19:48:40.812Z] removed user from space list
spacedeck_1  | DELETE /api/users/3cf5c610-e424-4edd-a9ea-6c8cbb3ea048?password=123456 - - ms - -
spacedeck_1  | [2020-05-31T19:49:46.024Z] websocket closed:  undefined undefined
spacedeck_1  | [2020-05-31T19:49:46.024Z] [websockets] socket undefined went offline in space undefined
spacedeck_1  | [2020-05-31T19:49:46.024Z] websocket not found to remove
spacedeck_1  | [2020-05-31T19:49:46.024Z] [websockets] socket undefined went offline in space null
spacedeck_1  | [2020-05-31T19:49:46.024Z] removed user from space list

**Comment by mntmn** [comment] 2020-06-02 18:49
Duplicate of #29

**Closed by mntmn** 2020-06-02 18:49 UTC

**Comment by comsyspro** [comment] 2021-05-05 13:12
today i also had some problems when trying to delete spaces and the user account. the solution was to set the **constraint property** to **ON DELETE CASCADE** in the database. now there is no restriction when deleting rows in the corresponding data tables.
